### ISSUE TITLE
There is no lifecycle rule in the module

### ISSUE THREAD

**Issue by samidbb** [dfds/aws-modules-s3#7]
This is needed so we can rotate logs when the s3 bucket is used for storing logs: inspiration here:  https://github.com/dfds-frontend/terraform-modules/blob/1a1f4b26f9f04f4879a6b14f9abfee152006e48b/aws/s3-bucket/main.tf#L18

Otherwise it will grow infinitely large and start to cost a lot of money

**Comment by avnes** [comment]
Closing this as it was implemeted in https://github.com/dfds/cloudplatform/issues/1948
